import Head from 'next/head'
import {BsFillMoonFill, BsFillSunFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillInstagram, AiFillFacebook} from 'react-icons/ai'
import Image from 'next/image'
import me from '../public/huha.png'
import design from '../public/design4.png'
import kurumi from '../public/kurumi.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import { useState } from 'react'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false)

  return (
    <>
    <div className={darkMode ? 'dark' : '' }>
      <Head>
        <title>EuReeka</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-2xl text-yellow-500 font-bold dark:text-yellow-400'>EUREEKA</h1>
            <ul className='flex items-center'>
              <li className='flex gap-5'>
                <BsFillMoonFill onClick={() => setDarkMode(!darkMode)}  className='cursor-pointer text-2xl dark:text-white' />
                <BsFillSunFill onClick={() => setDarkMode(!darkMode)}  className='cursor-pointer text-2xl dark:text-white' />
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 py-10'>
            <h2 className='text-5xl py-2 text-yellow-500 font-medium md:text-6xl dark:text-yellow-400'>EuReeka</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-red-500'>Kufufu</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>Eureka (Ancient Greek: εὕρηκα) is an interjection used to celebrate a discovery or invention. It is a transliteration of an exclamation attributed to Ancient Greek mathematician and inventor Archimedes.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-800 dark:text-yellow-400'>
            <a href="https://www.instagram.com/put_putraaaaaaaaa/" target='blank'><AiFillInstagram /></a>  
            <a href="https://www.facebook.com/dirham.putra.16/" target='blank'><AiFillFacebook /></a>            
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-yellow-500 to-yellow-400 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={me} alt='' layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 font-bold dark:text-red-500'>About Me</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Im 
              <span className='text-yellow-500 font-bold dark:text-yellow-400'> new</span> on programming.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              I like to drawing too.
            </p>
          </div>
          <div>
            <h3 className='text-3xl py-1 pt-5 font-bold dark:text-red-500'>Service For You</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
              Something i offer to you
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-yellow-400'>
              <Image className='mx-auto' src={design} alt='' width={200} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Simplify Design
              </h3>
              <p className='py-2'>
                Simplifying a design means to reduce its complexity. We view complexity as a way of characterizing designs from a given point of view, expressed as context, aspect and measure.
              </p>
              <h4 className='py-4 text-yellow-500 dark:text-black'>
                Tools i use for design
              </h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>CorelDraw X8</p>
              <p className='text-gray-800 py-1'>Photoshop</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-yellow-400'>
              <Image className='mx-auto' src={kurumi} alt='' width={200} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Simplify Design
              </h3>
              <p className='py-2'>
                Simplifying a design means to reduce its complexity. We view complexity as a way of characterizing designs from a given point of view, expressed as context, aspect and measure.
              </p>
              <h4 className='py-4 text-yellow-500 dark:text-black'>
                Tools i use for design
              </h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>CorelDraw X8</p>
              <p className='text-gray-800 py-1'>Photoshop</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-yellow-400'>
              <Image className='mx-auto' src={design} alt='' width={200} />
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Simplify Design
              </h3>
              <p className='py-2'>
                Simplifying a design means to reduce its complexity. We view complexity as a way of characterizing designs from a given point of view, expressed as context, aspect and measure.
              </p>
              <h4 className='py-4 text-yellow-500 dark:text-black'>
                Tools i use for design
              </h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>CorelDraw X8</p>
              <p className='text-gray-800 py-1'>Photoshop</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 font-bold dark:text-red-500'>Gallery</h3>
            <p className='py-2 dark:text-white'>
                Some of my project.
              </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} alt='' className='rounded-lg object-cover' layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} alt='' className='rounded-lg object-cover' layout='responsive' />
            </div>
          </div>
        </section>

        <section>
          <footer>
          <div className='bg-white py-10 dark:bg-gray-900 grid place-items-center'>
            <p className='text-center text-black dark:text-white'>Copyright © 2022 EuReeka</p>
        </div>
          </footer>
        </section>

      </main>
      </div>
    </>
  )
}